// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SupplierListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupplierListReq) Reset()         { *m = SupplierListReq{} }
func (m *SupplierListReq) String() string { return proto.CompactTextString(m) }
func (*SupplierListReq) ProtoMessage()    {}
func (*SupplierListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *SupplierListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupplierListReq.Unmarshal(m, b)
}
func (m *SupplierListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupplierListReq.Marshal(b, m, deterministic)
}
func (m *SupplierListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupplierListReq.Merge(m, src)
}
func (m *SupplierListReq) XXX_Size() int {
	return xxx_messageInfo_SupplierListReq.Size(m)
}
func (m *SupplierListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SupplierListReq.DiscardUnknown(m)
}

var xxx_messageInfo_SupplierListReq proto.InternalMessageInfo

type SupplierListResp struct {
	Code                 int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []*Supplier `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SupplierListResp) Reset()         { *m = SupplierListResp{} }
func (m *SupplierListResp) String() string { return proto.CompactTextString(m) }
func (*SupplierListResp) ProtoMessage()    {}
func (*SupplierListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{1}
}

func (m *SupplierListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupplierListResp.Unmarshal(m, b)
}
func (m *SupplierListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupplierListResp.Marshal(b, m, deterministic)
}
func (m *SupplierListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupplierListResp.Merge(m, src)
}
func (m *SupplierListResp) XXX_Size() int {
	return xxx_messageInfo_SupplierListResp.Size(m)
}
func (m *SupplierListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SupplierListResp.DiscardUnknown(m)
}

var xxx_messageInfo_SupplierListResp proto.InternalMessageInfo

func (m *SupplierListResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SupplierListResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SupplierListResp) GetData() []*Supplier {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SupplierListReq)(nil), "proto.SupplierListReq")
	proto.RegisterType((*SupplierListResp)(nil), "proto.SupplierListResp")
}

func init() { proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c) }

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0xc9, 0xcd,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x32, 0xe9, 0xf9, 0xf9,
	0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25, 0x99,
	0xf9, 0x79, 0xc5, 0x10, 0x45, 0x52, 0x62, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0xf1, 0xc5,
	0xa5, 0x05, 0x05, 0x39, 0x99, 0xa9, 0x45, 0x10, 0x71, 0x25, 0x41, 0x2e, 0xfe, 0x60, 0xa8, 0x88,
	0x4f, 0x66, 0x71, 0x49, 0x50, 0x6a, 0xa1, 0x52, 0x2a, 0x97, 0x00, 0xaa, 0x50, 0x71, 0x81, 0x90,
	0x10, 0x17, 0x4b, 0x72, 0x7e, 0x4a, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x98, 0x2d,
	0x24, 0xc1, 0xc5, 0x0e, 0x35, 0x54, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x15, 0x52,
	0xe6, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x56, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0x87, 0x58,
	0xa5, 0x07, 0x33, 0x34, 0x08, 0x2c, 0x69, 0x94, 0xc1, 0xc5, 0xea, 0x08, 0xf2, 0x85, 0x50, 0x3c,
	0x17, 0xbf, 0x7b, 0x6a, 0x09, 0xb2, 0x95, 0x42, 0x62, 0x68, 0x5a, 0xa0, 0x4e, 0x93, 0x12, 0xc7,
	0x2a, 0x5e, 0x5c, 0xa0, 0x24, 0xdd, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x51, 0x21, 0x61, 0xfd, 0x32,
	0x43, 0x7d, 0x70, 0xe0, 0xe8, 0xc3, 0x3c, 0x5a, 0x9c, 0xc4, 0x06, 0xd6, 0x64, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x90, 0x47, 0xe2, 0xd4, 0x36, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	GetSupplierList(ctx context.Context, in *SupplierListReq, opts ...grpc.CallOption) (*SupplierListResp, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetSupplierList(ctx context.Context, in *SupplierListReq, opts ...grpc.CallOption) (*SupplierListResp, error) {
	out := new(SupplierListResp)
	err := c.cc.Invoke(ctx, "/proto.Admin/GetSupplierList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	GetSupplierList(context.Context, *SupplierListReq) (*SupplierListResp, error)
}

// UnimplementedAdminServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (*UnimplementedAdminServer) GetSupplierList(ctx context.Context, req *SupplierListReq) (*SupplierListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupplierList not implemented")
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_GetSupplierList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplierListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetSupplierList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Admin/GetSupplierList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetSupplierList(ctx, req.(*SupplierListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSupplierList",
			Handler:    _Admin_GetSupplierList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
