// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_supplier.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RelationType int32

const (
	RelationType_RELATION_TYPE_INVALID RelationType = 0
	RelationType_RELATION_TYPE_QQ      RelationType = 1
	RelationType_RELATION_TYPE_TEL     RelationType = 2
	RelationType_RELATION_TYPE_EMAIL   RelationType = 3
	RelationType_RELATION_TYPE_ADDRESS RelationType = 4
)

var RelationType_name = map[int32]string{
	0: "RELATION_TYPE_INVALID",
	1: "RELATION_TYPE_QQ",
	2: "RELATION_TYPE_TEL",
	3: "RELATION_TYPE_EMAIL",
	4: "RELATION_TYPE_ADDRESS",
}

var RelationType_value = map[string]int32{
	"RELATION_TYPE_INVALID": 0,
	"RELATION_TYPE_QQ":      1,
	"RELATION_TYPE_TEL":     2,
	"RELATION_TYPE_EMAIL":   3,
	"RELATION_TYPE_ADDRESS": 4,
}

func (x RelationType) String() string {
	return proto.EnumName(RelationType_name, int32(x))
}

func (RelationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6683fe71c8fc7f9, []int{0}
}

type Supplier struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Contacts             []*Contact `protobuf:"bytes,4,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Supplier) Reset()         { *m = Supplier{} }
func (m *Supplier) String() string { return proto.CompactTextString(m) }
func (*Supplier) ProtoMessage()    {}
func (*Supplier) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6683fe71c8fc7f9, []int{0}
}

func (m *Supplier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Supplier.Unmarshal(m, b)
}
func (m *Supplier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Supplier.Marshal(b, m, deterministic)
}
func (m *Supplier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supplier.Merge(m, src)
}
func (m *Supplier) XXX_Size() int {
	return xxx_messageInfo_Supplier.Size(m)
}
func (m *Supplier) XXX_DiscardUnknown() {
	xxx_messageInfo_Supplier.DiscardUnknown(m)
}

var xxx_messageInfo_Supplier proto.InternalMessageInfo

func (m *Supplier) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Supplier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Supplier) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Supplier) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type Contact struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SupplierId           int64       `protobuf:"varint,2,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Title                string      `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Firstname            string      `protobuf:"bytes,4,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string      `protobuf:"bytes,5,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Relations            []*Relation `protobuf:"bytes,6,rep,name=relations,proto3" json:"relations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6683fe71c8fc7f9, []int{1}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contact) GetSupplierId() int64 {
	if m != nil {
		return m.SupplierId
	}
	return 0
}

func (m *Contact) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Contact) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Contact) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Contact) GetRelations() []*Relation {
	if m != nil {
		return m.Relations
	}
	return nil
}

type Relation struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId            int64        `protobuf:"varint,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	Type                 RelationType `protobuf:"varint,3,opt,name=type,proto3,enum=proto.RelationType" json:"type,omitempty"`
	Value                string       `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}
func (*Relation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6683fe71c8fc7f9, []int{2}
}

func (m *Relation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation.Unmarshal(m, b)
}
func (m *Relation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation.Marshal(b, m, deterministic)
}
func (m *Relation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation.Merge(m, src)
}
func (m *Relation) XXX_Size() int {
	return xxx_messageInfo_Relation.Size(m)
}
func (m *Relation) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation.DiscardUnknown(m)
}

var xxx_messageInfo_Relation proto.InternalMessageInfo

func (m *Relation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Relation) GetContactId() int64 {
	if m != nil {
		return m.ContactId
	}
	return 0
}

func (m *Relation) GetType() RelationType {
	if m != nil {
		return m.Type
	}
	return RelationType_RELATION_TYPE_INVALID
}

func (m *Relation) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.RelationType", RelationType_name, RelationType_value)
	proto.RegisterType((*Supplier)(nil), "proto.Supplier")
	proto.RegisterType((*Contact)(nil), "proto.Contact")
	proto.RegisterType((*Relation)(nil), "proto.Relation")
}

func init() { proto.RegisterFile("message_supplier.proto", fileDescriptor_c6683fe71c8fc7f9) }

var fileDescriptor_c6683fe71c8fc7f9 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0x86, 0xbf, 0xfe, 0x00, 0xed, 0xe1, 0x0b, 0xd6, 0x03, 0x68, 0x35, 0x1a, 0x09, 0x1b, 0x09,
	0x89, 0x2c, 0xf0, 0x0a, 0x1a, 0xe9, 0xa2, 0x49, 0x45, 0x19, 0x1a, 0x13, 0x57, 0x4d, 0xa5, 0xa3,
	0x69, 0x52, 0x68, 0xd3, 0x19, 0x8c, 0xdc, 0x82, 0x77, 0xe4, 0xdd, 0x19, 0xa7, 0x53, 0x10, 0x59,
	0xcd, 0x9c, 0xe7, 0x3d, 0xc9, 0xfb, 0x1c, 0x38, 0x59, 0x52, 0xc6, 0xa2, 0x37, 0x1a, 0xb2, 0x75,
	0x9e, 0xa7, 0x09, 0x2d, 0x46, 0x79, 0x91, 0xf1, 0x0c, 0x6b, 0xe2, 0xe9, 0x73, 0x30, 0xe6, 0x32,
	0xc0, 0x16, 0xa8, 0x49, 0x6c, 0x2b, 0x3d, 0x65, 0xa0, 0x11, 0x35, 0x89, 0x11, 0x41, 0x5f, 0x45,
	0x4b, 0x6a, 0xab, 0x3d, 0x65, 0x60, 0x12, 0xf1, 0x47, 0x1b, 0x1a, 0x51, 0x1c, 0x17, 0x94, 0x31,
	0x5b, 0x13, 0xb8, 0x1a, 0x71, 0x08, 0xc6, 0x22, 0x5b, 0xf1, 0x68, 0xc1, 0x99, 0xad, 0xf7, 0xb4,
	0x41, 0x73, 0xdc, 0x2a, 0xab, 0x46, 0x77, 0x25, 0x26, 0xdb, 0xbc, 0xff, 0xa5, 0x40, 0x43, 0xd2,
	0x83, 0xd6, 0x2b, 0x68, 0x56, 0xaa, 0x61, 0x12, 0x8b, 0x72, 0x8d, 0x40, 0x85, 0xbc, 0x18, 0x3b,
	0x50, 0xe3, 0x09, 0x4f, 0xa9, 0x14, 0x28, 0x07, 0xbc, 0x00, 0xf3, 0x35, 0x29, 0x18, 0x17, 0xc6,
	0xba, 0x48, 0x76, 0x00, 0xcf, 0xc1, 0x48, 0x23, 0x19, 0xd6, 0x44, 0xb8, 0x9d, 0xf1, 0x06, 0xcc,
	0x82, 0xa6, 0x11, 0x4f, 0xb2, 0x15, 0xb3, 0xeb, 0xc2, 0xfc, 0x48, 0x9a, 0x13, 0xc9, 0xc9, 0x6e,
	0xa3, 0xff, 0x01, 0x46, 0x85, 0x0f, 0xdc, 0x2f, 0x01, 0xe4, 0x8d, 0x3b, 0x75, 0x53, 0x12, 0x2f,
	0xc6, 0x6b, 0xd0, 0xf9, 0x26, 0x2f, 0xc5, 0x5b, 0xe3, 0xf6, 0x9f, 0x92, 0x60, 0x93, 0x53, 0x22,
	0x16, 0x7e, 0x4e, 0x7c, 0x8f, 0xd2, 0x75, 0x75, 0x48, 0x39, 0x0c, 0x3f, 0x15, 0xf8, 0xff, 0x7b,
	0x19, 0xcf, 0xa0, 0x4b, 0x5c, 0xdf, 0x09, 0xbc, 0x87, 0x69, 0x18, 0x3c, 0x3f, 0xba, 0xa1, 0x37,
	0x7d, 0x72, 0x7c, 0x6f, 0x62, 0xfd, 0xc3, 0x0e, 0x58, 0xfb, 0xd1, 0x6c, 0x66, 0x29, 0xd8, 0x85,
	0xe3, 0x7d, 0x1a, 0xb8, 0xbe, 0xa5, 0xe2, 0x29, 0xb4, 0xf7, 0xb1, 0x7b, 0xef, 0x78, 0xbe, 0xa5,
	0x1d, 0x16, 0x38, 0x93, 0x09, 0x71, 0xe7, 0x73, 0x4b, 0x7f, 0xa9, 0x0b, 0xf9, 0xdb, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf4, 0x20, 0xb3, 0x44, 0x60, 0x02, 0x00, 0x00,
}
