// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pager struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNum              int32    `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	Cursor               int64    `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore              bool     `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pager) Reset()         { *m = Pager{} }
func (m *Pager) String() string { return proto.CompactTextString(m) }
func (*Pager) ProtoMessage()    {}
func (*Pager) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Pager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pager.Unmarshal(m, b)
}
func (m *Pager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pager.Marshal(b, m, deterministic)
}
func (m *Pager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pager.Merge(m, src)
}
func (m *Pager) XXX_Size() int {
	return xxx_messageInfo_Pager.Size(m)
}
func (m *Pager) XXX_DiscardUnknown() {
	xxx_messageInfo_Pager.DiscardUnknown(m)
}

var xxx_messageInfo_Pager proto.InternalMessageInfo

func (m *Pager) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Pager) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *Pager) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

func (m *Pager) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func init() {
	proto.RegisterType((*Pager)(nil), "proto.Pager")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x05,
	0x5c, 0xac, 0x01, 0x89, 0xe9, 0xa9, 0x45, 0x42, 0xd2, 0x5c, 0x9c, 0x05, 0x89, 0xe9, 0xa9, 0xf1,
	0xc5, 0x99, 0x55, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x1c, 0x20, 0x81, 0xe0, 0xcc,
	0xaa, 0x54, 0x21, 0x09, 0x2e, 0x76, 0x10, 0xdb, 0xaf, 0x34, 0x57, 0x82, 0x09, 0x2c, 0x05, 0xe3,
	0x0a, 0x89, 0x71, 0xb1, 0x25, 0x97, 0x16, 0x15, 0xe7, 0x17, 0x49, 0x30, 0x2b, 0x30, 0x6a, 0x30,
	0x07, 0x41, 0x79, 0x20, 0x1d, 0x19, 0x89, 0xc5, 0xbe, 0xf9, 0x45, 0xa9, 0x12, 0x2c, 0x0a, 0x8c,
	0x1a, 0x1c, 0x41, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x62, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xd1, 0x90, 0x69, 0x33, 0x91, 0x00, 0x00, 0x00,
}
