// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type SaveUserReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveUserReq) Reset()         { *m = SaveUserReq{} }
func (m *SaveUserReq) String() string { return proto.CompactTextString(m) }
func (*SaveUserReq) ProtoMessage()    {}
func (*SaveUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{0}
}

func (m *SaveUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserReq.Unmarshal(m, b)
}
func (m *SaveUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserReq.Marshal(b, m, deterministic)
}
func (m *SaveUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserReq.Merge(m, src)
}
func (m *SaveUserReq) XXX_Size() int {
	return xxx_messageInfo_SaveUserReq.Size(m)
}
func (m *SaveUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserReq proto.InternalMessageInfo

func (m *SaveUserReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SaveUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaveUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// The response message containing the greetings
type SaveUserResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveUserResp) Reset()         { *m = SaveUserResp{} }
func (m *SaveUserResp) String() string { return proto.CompactTextString(m) }
func (*SaveUserResp) ProtoMessage()    {}
func (*SaveUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{1}
}

func (m *SaveUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserResp.Unmarshal(m, b)
}
func (m *SaveUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserResp.Marshal(b, m, deterministic)
}
func (m *SaveUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserResp.Merge(m, src)
}
func (m *SaveUserResp) XXX_Size() int {
	return xxx_messageInfo_SaveUserResp.Size(m)
}
func (m *SaveUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserResp proto.InternalMessageInfo

func (m *SaveUserResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SaveUserResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//UsersReq.
type UsersReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pager                *Pager   `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersReq) Reset()         { *m = UsersReq{} }
func (m *UsersReq) String() string { return proto.CompactTextString(m) }
func (*UsersReq) ProtoMessage()    {}
func (*UsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{2}
}

func (m *UsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersReq.Unmarshal(m, b)
}
func (m *UsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersReq.Marshal(b, m, deterministic)
}
func (m *UsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersReq.Merge(m, src)
}
func (m *UsersReq) XXX_Size() int {
	return xxx_messageInfo_UsersReq.Size(m)
}
func (m *UsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_UsersReq proto.InternalMessageInfo

func (m *UsersReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersReq) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

// The response message containing the greetings
type UsersResp struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*UsersResp_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pager                *Pager            `protobuf:"bytes,4,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UsersResp) Reset()         { *m = UsersResp{} }
func (m *UsersResp) String() string { return proto.CompactTextString(m) }
func (*UsersResp) ProtoMessage()    {}
func (*UsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{3}
}

func (m *UsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResp.Unmarshal(m, b)
}
func (m *UsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResp.Marshal(b, m, deterministic)
}
func (m *UsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResp.Merge(m, src)
}
func (m *UsersResp) XXX_Size() int {
	return xxx_messageInfo_UsersResp.Size(m)
}
func (m *UsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResp proto.InternalMessageInfo

func (m *UsersResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UsersResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UsersResp) GetData() []*UsersResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UsersResp) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

type UsersResp_Data struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	CreatedTime          string   `protobuf:"bytes,4,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersResp_Data) Reset()         { *m = UsersResp_Data{} }
func (m *UsersResp_Data) String() string { return proto.CompactTextString(m) }
func (*UsersResp_Data) ProtoMessage()    {}
func (*UsersResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{3, 0}
}

func (m *UsersResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResp_Data.Unmarshal(m, b)
}
func (m *UsersResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResp_Data.Marshal(b, m, deterministic)
}
func (m *UsersResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResp_Data.Merge(m, src)
}
func (m *UsersResp_Data) XXX_Size() int {
	return xxx_messageInfo_UsersResp_Data.Size(m)
}
func (m *UsersResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResp_Data proto.InternalMessageInfo

func (m *UsersResp_Data) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UsersResp_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersResp_Data) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UsersResp_Data) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

type CheckAccountReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAccountReq) Reset()         { *m = CheckAccountReq{} }
func (m *CheckAccountReq) String() string { return proto.CompactTextString(m) }
func (*CheckAccountReq) ProtoMessage()    {}
func (*CheckAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{4}
}

func (m *CheckAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccountReq.Unmarshal(m, b)
}
func (m *CheckAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccountReq.Marshal(b, m, deterministic)
}
func (m *CheckAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccountReq.Merge(m, src)
}
func (m *CheckAccountReq) XXX_Size() int {
	return xxx_messageInfo_CheckAccountReq.Size(m)
}
func (m *CheckAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccountReq proto.InternalMessageInfo

func (m *CheckAccountReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type CheckAccountResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAccountResp) Reset()         { *m = CheckAccountResp{} }
func (m *CheckAccountResp) String() string { return proto.CompactTextString(m) }
func (*CheckAccountResp) ProtoMessage()    {}
func (*CheckAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{5}
}

func (m *CheckAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccountResp.Unmarshal(m, b)
}
func (m *CheckAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccountResp.Marshal(b, m, deterministic)
}
func (m *CheckAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccountResp.Merge(m, src)
}
func (m *CheckAccountResp) XXX_Size() int {
	return xxx_messageInfo_CheckAccountResp.Size(m)
}
func (m *CheckAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccountResp proto.InternalMessageInfo

func (m *CheckAccountResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CheckAccountResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SaveUserReq)(nil), "proto.SaveUserReq")
	proto.RegisterType((*SaveUserResp)(nil), "proto.SaveUserResp")
	proto.RegisterType((*UsersReq)(nil), "proto.UsersReq")
	proto.RegisterType((*UsersResp)(nil), "proto.UsersResp")
	proto.RegisterType((*UsersResp_Data)(nil), "proto.UsersResp.Data")
	proto.RegisterType((*CheckAccountReq)(nil), "proto.CheckAccountReq")
	proto.RegisterType((*CheckAccountResp)(nil), "proto.CheckAccountResp")
}

func init() { proto.RegisterFile("system.proto", fileDescriptor_86a7260ebdc12f47) }

var fileDescriptor_86a7260ebdc12f47 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x25, 0x7f, 0xfd, 0x9a, 0x9b, 0xd0, 0xf6, 0x9b, 0xef, 0x13, 0x42, 0x70, 0x51, 0x67, 0x55,
	0x15, 0x1a, 0xac, 0x2e, 0x44, 0x70, 0xe1, 0xcf, 0xc6, 0x85, 0x20, 0xa9, 0xe2, 0x52, 0xc6, 0x64,
	0x88, 0x41, 0x93, 0x49, 0x33, 0xd3, 0x8a, 0x5b, 0x5f, 0xc1, 0x47, 0xf3, 0x09, 0x04, 0x37, 0xbe,
	0x85, 0x64, 0x92, 0xb6, 0xa9, 0x7f, 0x14, 0x5c, 0xe5, 0xe6, 0xcc, 0xbd, 0xe7, 0xdc, 0x39, 0x67,
	0xc0, 0xe6, 0x0f, 0x5c, 0xd0, 0xa4, 0x9f, 0xe5, 0x4c, 0x30, 0x64, 0xc8, 0x8f, 0xdb, 0x4a, 0x28,
	0xe7, 0x24, 0xa2, 0xbc, 0x84, 0xdd, 0xd5, 0x88, 0xb1, 0xe8, 0x8e, 0x7a, 0x24, 0x8b, 0x3d, 0x92,
	0xa6, 0x4c, 0x10, 0x11, 0xb3, 0xb4, 0x3a, 0xc5, 0x97, 0x60, 0x0d, 0xc9, 0x84, 0x5e, 0x70, 0x9a,
	0xfb, 0x74, 0x84, 0x1c, 0xf8, 0x43, 0x82, 0x80, 0x8d, 0x53, 0xe1, 0x28, 0x5d, 0xa5, 0x67, 0xfa,
	0xd3, 0x5f, 0x84, 0x40, 0x4f, 0x49, 0x42, 0x1d, 0x55, 0xc2, 0xb2, 0x46, 0x2e, 0x34, 0x33, 0xc2,
	0xf9, 0x3d, 0xcb, 0x43, 0x47, 0x93, 0xf8, 0xec, 0x1f, 0xef, 0x80, 0x3d, 0x27, 0xe6, 0x59, 0x31,
	0x1f, 0xb0, 0x90, 0x4a, 0x5a, 0xc3, 0x97, 0x35, 0xea, 0x80, 0x96, 0xf0, 0xa8, 0xa2, 0x2c, 0x4a,
	0x7c, 0x08, 0xcd, 0x62, 0x82, 0x17, 0xbb, 0x4c, 0x15, 0x95, 0x9a, 0x22, 0x06, 0x23, 0x23, 0x11,
	0xcd, 0xe5, 0x8c, 0x35, 0xb0, 0xcb, 0x5b, 0xf4, 0xcf, 0x0a, 0xcc, 0x2f, 0x8f, 0xf0, 0x9b, 0x02,
	0x66, 0x45, 0xb2, 0xac, 0x2e, 0x5a, 0x07, 0x3d, 0x24, 0x82, 0x38, 0x5a, 0x57, 0xeb, 0x59, 0x83,
	0x95, 0x8a, 0x76, 0xc6, 0xd2, 0x3f, 0x26, 0x82, 0xf8, 0xb2, 0x65, 0xbe, 0x82, 0xfe, 0xed, 0x0a,
	0x6e, 0x04, 0x7a, 0x31, 0x81, 0x5a, 0xa0, 0xc6, 0xa1, 0x94, 0xd6, 0x7c, 0x35, 0x0e, 0xbf, 0x34,
	0xb1, 0x66, 0xb9, 0xb6, 0x68, 0xf9, 0x1a, 0xd8, 0x41, 0x4e, 0x89, 0xa0, 0xe1, 0x95, 0x88, 0x13,
	0x2a, 0x05, 0x4d, 0xdf, 0xaa, 0xb0, 0xf3, 0x38, 0xa1, 0x78, 0x13, 0xda, 0x47, 0x37, 0x34, 0xb8,
	0x3d, 0x28, 0x47, 0x7e, 0x8c, 0x10, 0xef, 0x42, 0x67, 0xb1, 0x79, 0x59, 0x7b, 0x06, 0x2f, 0x0a,
	0x34, 0x86, 0xf2, 0xad, 0xa1, 0x13, 0x68, 0x4e, 0x73, 0x45, 0xa8, 0xba, 0x7b, 0xed, 0x05, 0xb9,
	0xff, 0x3e, 0x61, 0x3c, 0xc3, 0xff, 0x1f, 0x9f, 0x5f, 0x9f, 0xd4, 0x16, 0x36, 0xbd, 0xc9, 0x96,
	0x37, 0x2e, 0x5c, 0xdd, 0x53, 0x36, 0xd0, 0x29, 0xd8, 0xf5, 0x7d, 0x7e, 0x4b, 0xb7, 0x0f, 0x86,
	0x0c, 0x0c, 0xb5, 0x17, 0xe3, 0x1b, 0xb9, 0x9d, 0x8f, 0x79, 0xe2, 0xbf, 0x92, 0xc1, 0x42, 0x73,
	0x86, 0xeb, 0x86, 0xec, 0xd9, 0x7e, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x06, 0x02, 0xa0, 0x55,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemClient is the client API for System service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemClient interface {
	//SaveUser
	SaveUser(ctx context.Context, in *SaveUserReq, opts ...grpc.CallOption) (*SaveUserResp, error)
	//SaveUser
	CheckAccount(ctx context.Context, in *SaveUserReq, opts ...grpc.CallOption) (*SaveUserResp, error)
	Users(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersResp, error)
}

type systemClient struct {
	cc *grpc.ClientConn
}

func NewSystemClient(cc *grpc.ClientConn) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) SaveUser(ctx context.Context, in *SaveUserReq, opts ...grpc.CallOption) (*SaveUserResp, error) {
	out := new(SaveUserResp)
	err := c.cc.Invoke(ctx, "/proto.System/SaveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) CheckAccount(ctx context.Context, in *SaveUserReq, opts ...grpc.CallOption) (*SaveUserResp, error) {
	out := new(SaveUserResp)
	err := c.cc.Invoke(ctx, "/proto.System/CheckAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) Users(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersResp, error) {
	out := new(UsersResp)
	err := c.cc.Invoke(ctx, "/proto.System/Users", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServer is the server API for System service.
type SystemServer interface {
	//SaveUser
	SaveUser(context.Context, *SaveUserReq) (*SaveUserResp, error)
	//SaveUser
	CheckAccount(context.Context, *SaveUserReq) (*SaveUserResp, error)
	Users(context.Context, *UsersReq) (*UsersResp, error)
}

// UnimplementedSystemServer can be embedded to have forward compatible implementations.
type UnimplementedSystemServer struct {
}

func (*UnimplementedSystemServer) SaveUser(ctx context.Context, req *SaveUserReq) (*SaveUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUser not implemented")
}
func (*UnimplementedSystemServer) CheckAccount(ctx context.Context, req *SaveUserReq) (*SaveUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAccount not implemented")
}
func (*UnimplementedSystemServer) Users(ctx context.Context, req *UsersReq) (*UsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Users not implemented")
}

func RegisterSystemServer(s *grpc.Server, srv SystemServer) {
	s.RegisterService(&_System_serviceDesc, srv)
}

func _System_SaveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).SaveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.System/SaveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).SaveUser(ctx, req.(*SaveUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_CheckAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).CheckAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.System/CheckAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).CheckAccount(ctx, req.(*SaveUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_Users_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).Users(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.System/Users",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).Users(ctx, req.(*UsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _System_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveUser",
			Handler:    _System_SaveUser_Handler,
		},
		{
			MethodName: "CheckAccount",
			Handler:    _System_CheckAccount_Handler,
		},
		{
			MethodName: "Users",
			Handler:    _System_Users_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}
