// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type CreateUserReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{0}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CreateUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// The response message containing the greetings
type CreateUserResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResp) Reset()         { *m = CreateUserResp{} }
func (m *CreateUserResp) String() string { return proto.CompactTextString(m) }
func (*CreateUserResp) ProtoMessage()    {}
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{1}
}

func (m *CreateUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResp.Unmarshal(m, b)
}
func (m *CreateUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResp.Marshal(b, m, deterministic)
}
func (m *CreateUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResp.Merge(m, src)
}
func (m *CreateUserResp) XXX_Size() int {
	return xxx_messageInfo_CreateUserResp.Size(m)
}
func (m *CreateUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResp proto.InternalMessageInfo

func (m *CreateUserResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateUserResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//UsersReq.
type UsersReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pager                *Pager   `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersReq) Reset()         { *m = UsersReq{} }
func (m *UsersReq) String() string { return proto.CompactTextString(m) }
func (*UsersReq) ProtoMessage()    {}
func (*UsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{2}
}

func (m *UsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersReq.Unmarshal(m, b)
}
func (m *UsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersReq.Marshal(b, m, deterministic)
}
func (m *UsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersReq.Merge(m, src)
}
func (m *UsersReq) XXX_Size() int {
	return xxx_messageInfo_UsersReq.Size(m)
}
func (m *UsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_UsersReq proto.InternalMessageInfo

func (m *UsersReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersReq) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

// The response message containing the greetings
type UsersResp struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*UsersResp_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pager                *Pager            `protobuf:"bytes,4,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UsersResp) Reset()         { *m = UsersResp{} }
func (m *UsersResp) String() string { return proto.CompactTextString(m) }
func (*UsersResp) ProtoMessage()    {}
func (*UsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{3}
}

func (m *UsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResp.Unmarshal(m, b)
}
func (m *UsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResp.Marshal(b, m, deterministic)
}
func (m *UsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResp.Merge(m, src)
}
func (m *UsersResp) XXX_Size() int {
	return xxx_messageInfo_UsersResp.Size(m)
}
func (m *UsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResp proto.InternalMessageInfo

func (m *UsersResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UsersResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UsersResp) GetData() []*UsersResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UsersResp) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

type UsersResp_Data struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	CreatedTime          string   `protobuf:"bytes,4,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersResp_Data) Reset()         { *m = UsersResp_Data{} }
func (m *UsersResp_Data) String() string { return proto.CompactTextString(m) }
func (*UsersResp_Data) ProtoMessage()    {}
func (*UsersResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{3, 0}
}

func (m *UsersResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResp_Data.Unmarshal(m, b)
}
func (m *UsersResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResp_Data.Marshal(b, m, deterministic)
}
func (m *UsersResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResp_Data.Merge(m, src)
}
func (m *UsersResp_Data) XXX_Size() int {
	return xxx_messageInfo_UsersResp_Data.Size(m)
}
func (m *UsersResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResp_Data proto.InternalMessageInfo

func (m *UsersResp_Data) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UsersResp_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersResp_Data) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UsersResp_Data) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserReq)(nil), "proto.CreateUserReq")
	proto.RegisterType((*CreateUserResp)(nil), "proto.CreateUserResp")
	proto.RegisterType((*UsersReq)(nil), "proto.UsersReq")
	proto.RegisterType((*UsersResp)(nil), "proto.UsersResp")
	proto.RegisterType((*UsersResp_Data)(nil), "proto.UsersResp.Data")
}

func init() { proto.RegisterFile("system.proto", fileDescriptor_86a7260ebdc12f47) }

var fileDescriptor_86a7260ebdc12f47 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x95, 0xbf, 0xd2, 0xdc, 0x94, 0x50, 0xac, 0x56, 0x8a, 0x22, 0x86, 0xe2, 0xa9, 0x30,
	0x34, 0xa2, 0x48, 0x0c, 0x48, 0x2c, 0xc0, 0x0e, 0x0a, 0x30, 0x30, 0x21, 0x93, 0x58, 0x51, 0x24,
	0x12, 0xa7, 0xb1, 0x0b, 0x62, 0xe5, 0x15, 0x58, 0x78, 0x2f, 0x5e, 0x81, 0x85, 0xb7, 0x40, 0xbe,
	0x4d, 0xff, 0x50, 0x91, 0x98, 0x72, 0x7d, 0xec, 0xfb, 0x9d, 0xeb, 0x13, 0x43, 0x47, 0xbe, 0x4a,
	0xc5, 0x8b, 0x51, 0x55, 0x0b, 0x25, 0x88, 0x83, 0x9f, 0xd0, 0x2f, 0xb8, 0x94, 0x2c, 0xe3, 0x72,
	0x26, 0x87, 0x7b, 0x99, 0x10, 0xd9, 0x13, 0x8f, 0x58, 0x95, 0x47, 0xac, 0x2c, 0x85, 0x62, 0x2a,
	0x17, 0x65, 0xb3, 0x4b, 0xef, 0x61, 0xfb, 0xa2, 0xe6, 0x4c, 0xf1, 0x3b, 0xc9, 0xeb, 0x98, 0x4f,
	0x48, 0x00, 0x5b, 0x2c, 0x49, 0xc4, 0xb4, 0x54, 0x81, 0x31, 0x30, 0x86, 0x6e, 0x3c, 0x5f, 0x12,
	0x02, 0x76, 0xc9, 0x0a, 0x1e, 0x98, 0x28, 0x63, 0x4d, 0x42, 0x68, 0x57, 0x4c, 0xca, 0x17, 0x51,
	0xa7, 0x81, 0x85, 0xfa, 0x62, 0x4d, 0x4f, 0xc0, 0x5f, 0x45, 0xcb, 0x4a, 0x13, 0x12, 0x91, 0x72,
	0x04, 0x3b, 0x31, 0xd6, 0xa4, 0x0b, 0x56, 0x21, 0xb3, 0x06, 0xaa, 0x4b, 0x7a, 0x0e, 0x6d, 0xdd,
	0x21, 0xf5, 0x34, 0x73, 0x4f, 0x63, 0xc5, 0x93, 0x82, 0x53, 0xb1, 0x8c, 0xd7, 0xd8, 0xe3, 0x8d,
	0x3b, 0xb3, 0x9b, 0x8c, 0xae, 0xb5, 0x16, 0xcf, 0xb6, 0xe8, 0xb7, 0x01, 0x6e, 0x03, 0xf9, 0xaf,
	0x2f, 0x39, 0x00, 0x3b, 0x65, 0x8a, 0x05, 0xd6, 0xc0, 0x1a, 0x7a, 0xe3, 0x7e, 0x83, 0x5d, 0x50,
	0x46, 0x97, 0x4c, 0xb1, 0x18, 0x8f, 0x2c, 0x47, 0xb0, 0xff, 0x1c, 0x21, 0xcc, 0xc0, 0xd6, 0x1d,
	0xc4, 0x07, 0x33, 0x4f, 0xd1, 0xda, 0x8a, 0xcd, 0x3c, 0xdd, 0x18, 0xe3, 0x4a, 0xe8, 0xd6, 0x7a,
	0xe8, 0xfb, 0xd0, 0x49, 0x30, 0xc4, 0xf4, 0x41, 0xe5, 0x05, 0x47, 0x43, 0x37, 0xf6, 0x1a, 0xed,
	0x36, 0x2f, 0xf8, 0xf8, 0xc3, 0x80, 0xd6, 0x0d, 0x3e, 0x04, 0x72, 0x05, 0xb0, 0x8c, 0x9c, 0xf4,
	0x9a, 0xb1, 0xd6, 0x7e, 0x70, 0xd8, 0xdf, 0xa0, 0xca, 0x8a, 0xf6, 0xde, 0x3e, 0xbf, 0xde, 0x4d,
	0x9f, 0xba, 0xd1, 0xf3, 0x51, 0x34, 0xd5, 0x97, 0x3e, 0x35, 0x0e, 0xc9, 0x19, 0x38, 0x18, 0x00,
	0xd9, 0x59, 0x8f, 0x63, 0x12, 0x76, 0x7f, 0xe7, 0x43, 0x77, 0x91, 0xe0, 0x91, 0x25, 0xe1, 0xb1,
	0x85, 0x67, 0x8e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x2e, 0x2c, 0x0c, 0xa9, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemClient is the client API for System service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemClient interface {
	//CreateUser
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
	Users(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersResp, error)
}

type systemClient struct {
	cc *grpc.ClientConn
}

func NewSystemClient(cc *grpc.ClientConn) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	out := new(CreateUserResp)
	err := c.cc.Invoke(ctx, "/proto.System/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) Users(ctx context.Context, in *UsersReq, opts ...grpc.CallOption) (*UsersResp, error) {
	out := new(UsersResp)
	err := c.cc.Invoke(ctx, "/proto.System/Users", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServer is the server API for System service.
type SystemServer interface {
	//CreateUser
	CreateUser(context.Context, *CreateUserReq) (*CreateUserResp, error)
	Users(context.Context, *UsersReq) (*UsersResp, error)
}

// UnimplementedSystemServer can be embedded to have forward compatible implementations.
type UnimplementedSystemServer struct {
}

func (*UnimplementedSystemServer) CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedSystemServer) Users(ctx context.Context, req *UsersReq) (*UsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Users not implemented")
}

func RegisterSystemServer(s *grpc.Server, srv SystemServer) {
	s.RegisterService(&_System_serviceDesc, srv)
}

func _System_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.System/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).CreateUser(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_Users_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).Users(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.System/Users",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).Users(ctx, req.(*UsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _System_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _System_CreateUser_Handler,
		},
		{
			MethodName: "Users",
			Handler:    _System_Users_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}
